# Generated by Django 4.2.11 on 2024-03-14 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mfo', models.CharField(max_length=5)),
                ('branch_id', models.CharField(max_length=5)),
                ('application_id', models.IntegerField()),
                ('state', models.IntegerField()),
                ('claim_id', models.IntegerField()),
                ('region_id', models.CharField(max_length=5)),
                ('district_id', models.CharField(max_length=5)),
                ('client_type', models.CharField(max_length=20)),
                ('client_name', models.CharField(max_length=255)),
                ('client_id', models.BigIntegerField()),
                ('credit_sum', models.FloatField()),
                ('credit_percent', models.FloatField()),
                ('credit_date', models.DateField()),
                ('credit_term_date', models.DateField(null=True)),
                ('change_date', models.DateField()),
                ('credit_num', models.CharField(max_length=15, null=True)),
                ('credit_purpose_code', models.CharField(max_length=20, null=True)),
                ('credit_purpose_name', models.CharField(max_length=255, null=True)),
                ('credit_account', models.CharField(max_length=25, null=True)),
                ('overdue_debt_account', models.CharField(max_length=25, null=True)),
                ('first_pay_date', models.DateField(null=True)),
                ('last_pay_date', models.DateField(null=True)),
                ('total_pay_sum', models.FloatField(null=True)),
                ('debt_sum', models.FloatField(null=True)),
                ('overdue_debt_sum', models.FloatField(null=True)),
                ('overdue_debt_date', models.DateField(null=True)),
                ('overdue_debt_day', models.IntegerField(null=True)),
                ('next_month_pay_sum', models.FloatField(null=True)),
                ('account_16309_sum', models.CharField(max_length=25, null=True)),
                ('account_16323_sum', models.CharField(max_length=25, null=True)),
                ('account_16377_sum', models.CharField(max_length=25, null=True)),
                ('account_16379_sum', models.CharField(max_length=25, null=True)),
                ('account_16405_sum', models.CharField(max_length=25, null=True)),
                ('account_16413_sum', models.CharField(max_length=25, null=True)),
            ],
        ),
    ]
