# Generated by Django 4.2.11 on 2024-03-15 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_district_id_application_district_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='state',
            field=models.CharField(max_length=255),
        ),
    ]
