# Generated by Django 4.2.11 on 2024-03-15 10:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_application_change_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
