# Generated by Django 4.2.11 on 2024-03-20 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_application_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Informationapp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_id', models.CharField(max_length=10)),
                ('mfo', models.CharField(max_length=10)),
                ('account', models.CharField(max_length=20)),
                ('account_status', models.IntegerField(default=0)),
                ('turnover_db_20208', models.BigIntegerField(default=0)),
                ('turnover_cr_20208', models.BigIntegerField(default=0)),
                ('turnover_cr_20218', models.BigIntegerField(default=0)),
                ('turnover_db_20218', models.BigIntegerField(default=0)),
                ('turnover_db_20212', models.BigIntegerField(default=0)),
                ('turnover_cr_20212', models.BigIntegerField(default=0)),
                ('saldo_90963', models.BigIntegerField(default=0)),
            ],
        ),
    ]
