# Generated by Django 4.2.11 on 2024-03-27 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_clientinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='credit_sum',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='application',
            name='total_pay_sum',
            field=models.BigIntegerField(null=True),
        ),
    ]
