# Generated by Django 4.2.11 on 2024-03-28 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_application_credit_sum_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='loan_id',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
