# Generated by Django 4.2.11 on 2024-04-01 06:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_application_debt_sum'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditPay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('loan_id', models.IntegerField()),
                ('nibbd_code', models.CharField(max_length=12)),
                ('mfo', models.CharField(max_length=6)),
                ('account', models.CharField(max_length=25)),
                ('branch_id', models.CharField(max_length=10)),
                ('account_status', models.BooleanField()),
                ('turnover_db_20208', models.BigIntegerField(null=True)),
                ('turnover_cr_20208', models.BigIntegerField(null=True)),
                ('turnover_cr_20218', models.BigIntegerField(null=True)),
                ('turnover_db_20218', models.BigIntegerField(null=True)),
                ('turnover_cr_22618', models.BigIntegerField(null=True)),
                ('turnover_db_22618', models.BigIntegerField(null=True)),
                ('turnover_db_20212', models.BigIntegerField(null=True)),
                ('turnover_cr_20212', models.BigIntegerField(null=True)),
                ('saldo_90963', models.BigIntegerField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Informationapp',
        ),
    ]
