# Generated by Django 4.2.11 on 2024-04-17 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_remove_application_claim_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_id', models.CharField(max_length=10)),
                ('cl_mfo', models.CharField(max_length=10)),
                ('cl_account', models.CharField(max_length=25)),
                ('cl_name', models.CharField(max_length=255)),
                ('cl_id', models.CharField(max_length=10)),
                ('ca_mfo', models.CharField(max_length=10)),
                ('ca_account', models.CharField(max_length=20)),
                ('ca_name', models.CharField(max_length=255)),
                ('ca_id', models.BigIntegerField()),
                ('doc_id', models.CharField(max_length=10)),
                ('doc_date', models.DateField()),
                ('doc_num', models.DateField()),
                ('pay_sum', models.BigIntegerField()),
                ('pay_code', models.CharField(max_length=10)),
                ('pay_note', models.CharField(max_length=200)),
                ('pay_state', models.CharField(max_length=25)),
                ('pay_date', models.DateField()),
            ],
        ),
    ]
