# Generated by Django 4.2.11 on 2024-04-18 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_creditpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditpayment',
            name='loan_id',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='creditpayment',
            name='doc_num',
            field=models.IntegerField(),
        ),
    ]
