# Generated by Django 4.2.11 on 2024-04-18 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_creditpayment_loan_id_alter_creditpayment_doc_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditpayment',
            name='pay_state',
            field=models.IntegerField(),
        ),
    ]
