# Generated by Django 4.2.11 on 2024-05-03 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_creditpayment_pay_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditpay',
            name='saldo_90963',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='creditpay',
            name='turnover_cr_20208',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='creditpay',
            name='turnover_cr_20212',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='creditpay',
            name='turnover_cr_20218',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='creditpay',
            name='turnover_cr_22618',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='creditpay',
            name='turnover_db_20208',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='creditpay',
            name='turnover_db_20212',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='creditpay',
            name='turnover_db_20218',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='creditpay',
            name='turnover_db_22618',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
