# Generated by Django 4.2.11 on 2024-05-03 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_creditpay_saldo_90963_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditpay',
            name='turnover_cr_22618',
        ),
        migrations.RemoveField(
            model_name='creditpay',
            name='turnover_db_22618',
        ),
    ]
