# Generated by Django 4.2.11 on 2024-05-18 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_addclients'),
    ]

    operations = [
        migrations.AddField(
            model_name='addclients',
            name='doc_num',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
